name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  INPUT_TEST_VAR:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.INPUT_TEST_VAR }}