name: Test Workflow
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./saucelabs-action
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
