name: Test Workflow
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./saucelabs-action
        with:
          APK_PATH: $APK_PATH
          TEST_APK_PATH: "app test"
          DATA_CENTER: "eu-central-1"
          DEVICE_NAME: "Google Pixel GoogleAPI Emulator,platformVersion=7.0"
        env:
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
